### ISSUE TITLE
Rank sorted by Client ID and not Level/Time - Need help.

### ISSUE THREAD

**Issue by P-Philipp** [Newcomer1989/TSN-Ranksystem#872]
Ranksystem Version | 1.3._19_
Are you using TeamSpeak or TeaSpeak? | TeamSpeak
Link to your Ranksystem Stats page | https://gamerstube.eu/ranksystem/stats/index.php
Pastebin Link to your Ranksystem Log | https://pastebin.com/jCQ2JirG

---

### 1) What did you do?
Update to PHP8 and everything crapped itself so I reverted to 7.4

### 2) What result did you get?
Long story short, I reverted back to 7.4 but when the rankup list is sorted by time or current servergroup the actual Rank is seemingly assigned randomly. However, when I sort it by unique Client-ID the Ranks are sorted correctly. See attached gif.

Sorted by sum. active time: https://i.imgur.com/mPEz415.png
Sorted by unique Client-ID: https://i.imgur.com/Iq0rqim.png

### 3) What result did you expect?
It working like it used to :D

Any ideas on how to fix this are greatly appreciated.

**Comment by Newcomer1989** [comment]
The sorting is depending on the 'time mode' which will be used (Webinterface -> Rank -> Core -> time mode).

We are running the following SQL command to sort it for 'active time':
```
SET @a:=0;
UPDATE `user` AS `u` INNER JOIN (SELECT @a:=@a+1 `nr`,`uuid` FROM `user` WHERE `except`<2 ORDER BY (`count` - `idle`) DESC) AS `s` USING (`uuid`) SET `u`.`rank`=`s`.`nr`;
```

This runs every 15 Minutes. Your logfile above is about ~10 minutes. 

Perhaps you can run the SQL command above manually on your database to check, it do not run into troubles.

Have a look your listing is changed.
If not, which exceptions do you have (Webinterface -> Rank -> Exceptions)?
And do you show excepted clients in the Rank list (Webinterface -> Stats Page -> List Rankup -> excepted client)?

**Comment by P-Philipp** [comment]
Sorry for the late reply.

### Time mode 
is set to active time.
![image](https://user-images.githubusercontent.com/39447792/172072460-d963fb5f-7cfa-49f7-8031-b29c77b67c1b.png)


### Running the command on the database manually 
Ran successfully

`MariaDB [(none)]> use ranking
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [ranking]> SET @a:=0;
Query OK, 0 rows affected (0.000 sec)

MariaDB [ranking]> UPDATE `user` AS `u` INNER JOIN (SELECT @a:=@a+1 `nr`,`uuid` FROM `user` WHERE `except`<2 ORDER BY (`count` - `idle`) DESC) AS `s` USING (`uuid`) SET `u`.`rank`=`s`.`nr`;
Query OK, 0 rows affected (0.045 sec)
Rows matched: 6916  Changed: 0  Warnings: 0`

### Webinterface -> Rank -> Exceptions
![image](https://user-images.githubusercontent.com/39447792/172072432-89d90737-135c-4dad-88cf-53601bf454d1.png)

### Webinterface -> Stats Page -> List Rankup -> excepted client
Excepted clients are set to "ON"
![image](https://user-images.githubusercontent.com/39447792/172072498-8e50f4bf-a2f8-40bf-8627-8da95037025a.png)

**Comment by Newcomer1989** [comment]
The SQL statement seems to be running fine.

Did anything changed after? Is the Ranklist still wrong storted?

**Comment by P-Philipp** [comment]
just an update for this issue:

just talked with @Newcomer1989 on teamspeak and we found out it seems to be an issue with MariaDB versions from 10.6 and later.
Will report back here once the Ranksystem gets updated.

**Comment by Newcomer1989** [comment]
We built a new beta version, which should solve the problem:
1.3.20-beta-3

It can be tested on the 'beta' update-channel.

**Comment by P-Philipp** [comment]
Hello,

Sorry I was away for a couple days.
I am now on `Ranksystem Version: 1.3.20 (on Update-Channel: beta)`
and the issue still persists.

**Comment by Newcomer1989** [comment]
I saw to late, the database version is "5.5.5-10.6.8-MariaDB-1" for you.

We checked again ">= 10.6", which will not work, if the Version begins with "5.5.5".

With the current beta version "1.3.21-beta-1" it should be fixed... I hope so 😅

**Comment by P-Philipp** [comment]
Sorry for the late reply again.

Checked just now on this version: 1.3.21-beta-1
and it works as intended.

Thank you for all your help!
